target ‘AIAnimationDemo’ do
    pod 'pop', :git => 'https://github.com/facebook/pop.git'
    pod 'MLTransition', '~> 2.1.2'#滑动返回
    pod 'AFNetworking', '~> 3.0'  #网络请求
    pod 'Canvas', '~> 0.1.2'      #动画
end
