target ‘AIAnimationDemo’ do
    inhibit_all_warnings!         #禁止所有警告
    pod 'pop', :git => 'https://github.com/facebook/pop.git'
    pod 'MLTransition', '~> 2.1.2'#滑动返回
    pod 'AFNetworking', '~> 3.0'  #网络请求
    pod 'Canvas', '~> 0.1.2'      #动画
    pod 'KMCGeigerCounter'        #检测app fps是否流畅 左边值越大越不流畅
    pod 'ResearchKit', '~> 1.3.1' #苹果官方的医疗SKD
    pod 'ReactiveObjC', '~> 1.0.1'#链式编程
    pod 'Bugly'                   #腾讯bug管理系统
end
